### ISSUE TITLE
Vanilla RF inversion.

### ISSUE THREAD

**Issue by Adenialzz** [wangjiangshan0725/RF-Solver-Edit#11]
Hi. How can we implement vanilla rf inversion for testing ? Just need to add one line
```python
timesteps = timesteps[::-1]
```
to official flux sampling code ? any other changes ?

**Comment by wangjiangshan0725** [comment]
Dear @Adenialzz , thanks for your interest in our work!

To implement vanilla rf inversion, you need to modify the model's input from noise to the latent of image, while ensuring that the timestep starts from 0 and increases to 1.

**Comment by Adenialzz** [comment]
yes. 

1. I use `ae.encoder` to encode an input image, and reverse timesteps with `timesteps = timesteps[::-1]`,
2. then I use the model to do vanilla rf inversion (add noise) thus it is expected to get the latent noise of this input image
3. After that, I use timesteps before reversed to denoise this latent noise, and get a latent image. 
4. When I finally use `ae.decoder` to decode this latent to pixel space, it should looked similar with the original input image, right? (with some changes but same semantics)


```python
img = Image.open('xxx.png')
latent_img = encode(img, ae)
ts = get_timesteps(n_steps)
rev_ts = ts[:: -1]

for loop with rev_ts:
    latent_noise = model(latent_img, xxx)

for loop with ts:
    latent_img = model(latent_noise, xxx)

rect_img = decode(latent_img, ae)
```
thus $$\text{img} \approx \text{latent-img}$$

is this vanilla rf inversion process correct and complete ?

**Comment by wangjiangshan0725** [comment]
@Adenialzz The pesudo code is correct. You can refer to our code for more detailed implementation!

**Comment by Adenialzz** [comment]
thanks. Of course I will read and understand your code carefully, your work is valuable, and thanks for open sourcing.
