### ISSUE TITLE
The value of guidance scale during inversion

### ISSUE THREAD

**Issue by Xilluill** [wangjiangshan0725/RF-Solver-Edit#16]
感谢你们的杰出工作！我最近正在尝试你们的demo，我发现在inversion过程中将guidance略微调大例如到3.5，就会经常导致无意义图片，对于此你们有什么看法吗？

**Comment by wangjiangshan0725** [comment]
您好！目前现有工作在inversion的时候guidance都为1或0，如FLATTEN（ICLR2024）、Smooth Diffusion（CVPR2024）等。这是因为推导出来的inversion公式不包含classifier free guidance的部分，如果把inversion过程中的guidance调大就会导致无意义的图片。

**Comment by Xilluill** [comment]
Thanks to your reply! I have no more question.
