### ISSUE TITLE
How to Enable Multiple Images Inference with Customizable Batch Size

### ISSUE THREAD

**Issue by XuwuChen443** [wangjiangshan0725/RF-Solver-Edit#17]
the inference process seems to only handle one image at a time

**Comment by wangjiangshan0725** [comment]
Hi,  @XuwuChen443 . Thanks for your interest in our work!

Our code can be modified to support the multiple images inference simply. To achieve this, you need to modify the ``prepare`` function in ``sampling.py``.

**Comment by xixohoej** [comment]
thanks, i still have a question that when infering multiple images, must all images have the same resolution?

**Comment by XuwuChen443** [comment]
Thank you for the information. I'd like to inquire further: when inferring multiple images simultaneously, is it necessary for all images to have the same resolution?

**Comment by wangjiangshan0725** [comment]
Yes, all image in one batch should have the same resolution. If you want to edit image with different resolution, maybe you can firstly resize them and then do the editing!

**Comment by XuwuChen443** [comment]
@wangjiangshan0725 Hi, After implementing vectorized batch processing for multiple images, I noticed that the inference time still grows linearly with the number of images. Time profiling revealed that the two `denoise` operations are the main bottlenecks, despite no explicit per-image loops in the function.

Additionally, I found that the `prepare` function seems to work with vectorized input without modifications.

**Comment by voodoohop** [comment]
@XuwuChen443 this is a common problem with Stable Diffusion and Flux-like architectures. In my experience processing in batch does not yield noticeable speedups to just doing sequentially.

**Comment by XuwuChen443** [comment]
@voodoohop Thank you so much for sharing your valuable experience! This insight is really helpful for my implementation. I'm curious if you happen to know what causes this behavior?

**Comment by voodoohop** [comment]
I am not sure about the details but there seem to be some approaches that allow more efficient parallelisation of diffusion models  

like https://github.com/xdit-project/xDiT/

not sure how complicated integrating the two approaches would be.

**Comment by XuwuChen443** [comment]
@voodoohop Thank you for your detailed suggestion! I've checked the xDiT repository and it looks very promising for improving diffusion model parallelization. Really appreciate you taking the time to share this resource!
