### ISSUE TITLE
Question about image diff when prompt changes.

### ISSUE THREAD

**Issue by Adenialzz** [wangjiangshan0725/RF-Solver-Edit#2]
Hi, thanks for your open-sourcing.

When I tried different prompts (brown dog -> white cat), the original image changed a little. I think it should be kept unchanged, why this happend?

![cmp](https://github.com/user-attachments/assets/2f2d23cb-c956-4a83-a00b-bac4cb09aba9)

**Comment by wangjiangshan0725** [comment]
Thanks for your interest in out work!

Different prompts present varying levels of difficulty for the model, leading to different editing outcomes. To address this issue, we suggest slightly adjusting the --inject and --timestep, selecting the best results. 

increasing the parameter --inject can obtain the following results:

<img width="628" alt="image" src="https://github.com/user-attachments/assets/16ddfb85-69f4-4fd5-91c7-d817cded4942">

You could further tune the parameter for better results.

**Comment by wangjiangshan0725** [comment]
Thanks for your interest in out work!

Different prompts present varying levels of difficulty for the model, leading to different editing outcomes. To address this issue, we suggest slightly adjusting the --inject and --timestep, selecting the best results.

**Comment by Adenialzz** [comment]
OK. I will try more and read the paper in detail. Thanks, nice work.
