### ISSUE TITLE
Baseline Hyperparam

### ISSUE THREAD

**Issue by Bili-Sakura** [wangjiangshan0725/RF-Solver-Edit#4]
Awesome!
I wonder how you chose hyper parameters when conducting other image editing techniques/models for comparison. For example, InstructPix2Pix takes image_guidance_scale and guidance_scale for achieving best performance. Also, I wonder which sampling schedule you choose as well as sampling steps.

**Comment by wangjiangshan0725** [comment]
Thanks for your interest in our work! For RF-inversion, we use the **ComfyUI re-implementation** (https://github.com/logtd/ComfyUI-Fluxtapoz). For other baseline methods we adopt the implementation from **diffusers**. We will include more details about the hyperparam in the updated version of our paper, which will be available in one or two weeks.

**Comment by HolmesShuan** [comment]
> Admittedly this has some small differences between the example images in the paper, but it's very close. Will be updating as I find the issue. It's currently my recommended way to unsample an image for editing or style transfer.

According to the README, it appears that the current repository has some bugs.
