### ISSUE TITLE
关于公式的推导，是否有计算二阶的必要。

### ISSUE THREAD

**Issue by wuutiing** [wangjiangshan0725/RF-Solver-Edit#7]
![image](https://github.com/user-attachments/assets/d1707dc9-ef4f-4b34-950b-8ffbcde97124)

我疑惑流程最后的公式里，完全可以化简为 V_(ti+△ti) * (t_(i-1) - t_i)，计算 v_ti^(1) 又有什么必要呢。
相应的代码在：https://github.com/wangjiangshan0725/RF-Solver-Edit/blob/7d314ea4ddae2a1960bdaa21a8a74edb5ffd2c2d/src/flux/sampling.py#L133-L134

望解答

**Comment by wangjiangshan0725** [comment]
感谢您对我们工作的关注。使用△ti=1/2 (t_(i-1) - t_i)计算导数仅仅是一个估算的方法，可以被其他估算导数的方法代替。如果将其表达式代入进一步简化会降低公式的普适性，也无法拓展到更高阶的形式。我们的主要贡献在于**推导出RFsampler的 高阶形式（即文章中的公式9）**，具体的RFsolver算法是公式9的一个特例（即一阶展开）。
