### ISSUE TITLE
[Question] Only mean value used in AE's DiagonalGaussian?

### ISSUE THREAD

**Issue by HolmesShuan** [wangjiangshan0725/RF-Solver-Edit#9]
<img width="1218" alt="image" src="https://github.com/user-attachments/assets/c4fa78ae-42ff-4e78-a8c9-d9de32b60f44">

The left part of this image is from the official FLUX implementation, while the right part is from the RF-Solver implementation. I am curious about the reasoning behind the authors’ decision to apply this approach. Could this setting have been designed to achieve higher fidelity, potentially at the expense of diversity?

**Comment by wangjiangshan0725** [comment]
Thanks for your interst in our work!

We remove the variance so that the results in the paper can be precisely reproduced based on the provided code. You can also add this part, which will not significantly affect the results.

**Comment by HolmesShuan** [comment]
I personally think fixing the random seed should work if reproducing the results is the main concern.
